export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FAIL = 'UPDATE_USER_DETAILS_FAIL';
export const UPDATE_USER_DETAILS_RESET = 'UPDATE_USER_DETAILS_RESET';

export const CHANGE_USER_LOGIN_REQUEST = 'CHANGE_USER_LOGIN_REQUEST';
export const CHANGE_USER_LOGIN_SUCCESS = 'CHANGE_USER_LOGIN_SUCCESS';
export const CHANGE_USER_LOGIN_FAIL = 'CHANGE_USER_LOGIN_FAIL';
export const CHANGE_USER_LOGIN_RESET = 'CHANGE_USER_LOGIN_RESET';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_SELLERS_REQUEST = 'GET_SELLERS_REQUEST';
export const GET_SELLERS_SUCCESS = 'GET_SELLERS_SUCCESS';
export const GET_SELLERS_FAIL = 'GET_SELLERS_FAIL';

export const GET_SELLER_REQUEST = 'GET_SELLER_REQUEST';
export const GET_SELLER_SUCCESS = 'GET_SELLER_SUCCESS';
export const GET_SELLER_FAIL = 'GET_SELLER_FAIL';
export const GET_SELLER_RESET = 'GET_SELLER_RESET';

export const USER_LOGOUT = 'USER_LOGOUT';
